### ISSUE TITLE
files are infected with virus

### ISSUE THREAD

**Issue by zacwithhacks** [ddf8196/BetterRenderDragon#80]
the download page has been infected with a virus so when you download the files you cant use them because your antivirus will not let you and with bitdefender i scanned the file and it is infected with some kind of teddy virus please fix this

**Comment by EnderBoy2000** [comment]
the files are not infected, its just antivirus doesnt like programs that inject into other programs and just .bat files altogetherOn 26. Jun 2024, at 08:58, zacwithhacks ***@***.***> wrote:﻿
the download page has been infected with a virus so when you download the files you cant use them because your antivirus will not let you and with bitdefender i scanned the file and it is infected with some kind of teddy virus please fix this

**Comment by miqumi** [comment]
> the download page has been infected with a virus so when you download the files you cant use them because your antivirus will not let you and with bitdefender i scanned the file and it is infected with some kind of teddy virus please fix this

did you REALLY make a new account just to post smthn bout false positive son

**Comment by zacwithhacks** [comment]
Miqumi

If it was a false positive my system wouldn't have constantly kept quarantining the files and I would be able to delete the files without using Bitdefender to force delete them

**Comment by Arctrometa** [comment]
> Miqumi
> 
> If it was a false positive my system wouldn't have constantly kept quarantining the files and I would be able to delete the files without using Bitdefender to force delete them

BetterRD injects and messes with the memory of an application (that being Minecraft), that's why anti virus software is flagging BetterRD as a malware. It is just a false positive. You are free to go through the code to make sure of it yourself. Adding an exception to the BetterRD directory in your antivirus is recommended .

**Comment by zacwithhacks** [comment]
It also flags the dll the only issue I have with this is other files that inject into minecraft and their injectors ex: horizon client aren't flagged so idk

**Comment by Arctrometa** [comment]
> It also flags the dll the only issue I have with this is other files that inject into minecraft and their injectors ex: horion client aren't flagged so idk
Nothing we can do about this at the moment.

**Comment by zacwithhacks** [comment]
Ok ill exempt brd from my antivirus

**Comment by zacwithhacks** [comment]
Fixed it

**Comment by Yarolsawmor** [comment]
> Исправил это
здравствуйте можете сказать как вы это пофиксили

**Comment by miqumi** [comment]
> It also flags the dll the only issue I have with this is other files that inject into minecraft and their injectors ex: horion client aren't flagged so idk

pretty sure Horion stores it's dll in a different way..

**Comment by miqumi** [comment]
> > Исправил это
> здравствуйте можете сказать как вы это пофиксили

Exclude the folder from your Antivirus
[Guide for Windows Defender](https://docs.rackspace.com/docs/set-windows-defender-folder-exclusions#step-1-set-the-exclusion-through-windows-security)

Исключите папку из антивируса
[руководство для Windows Defender](https://docs.rackspace.com/docs/set-windows-defender-folder-exclusions#step-1-set-the-exclusion-through-windows-security)
