### ISSUE TITLE
when using shaders i get a white screen

### ISSUE THREAD

**Issue by Avisator1** [ddf8196/BetterRenderDragon#90]
so i have been using better RD for like a while now, and before on a previous version of MCPE(1.20.10), the fog shaders that i was using was completeley working and was fine, but now its not working anymore on the latest version of the game. Can anyone take a look and try to help me on this issue?

![image](https://github.com/user-attachments/assets/6fe10d01-fa17-4b99-981d-0e112f16924f)

here is the fog shader if you need:
[FogShaderR.zip](https://github.com/user-attachments/files/16266571/FogShaderR.zip)

**Comment by EnderBoy2000** [comment]
your shader is outdated and does not support 1.21On 17. Jul 2024, at 15:55, Avisator ***@***.***> wrote:﻿
so i have been using better RD for like a while now, and before on a previous version of MCPE(1.20.10), the fog shaders that i was using was completeley working and was fine, but now its not working anymore on the latest version of the game. Can anyone take a look and try to help me on this issue?
image.png (view on web)
here is the fog shader if you need:
FogShaderR.zip

**Comment by Avisator1** [comment]
> your shader is outdated and does not support 1.21On 17. Jul 2024, at 15:55, Avisator ***@***.***> wrote:﻿ so i have been using better RD for like a while now, and before on a previous version of MCPE(1.20.10), the fog shaders that i was using was completeley working and was fine, but now its not working anymore on the latest version of the game. Can anyone take a look and try to help me on this issue? image.png (view on web) here is the fog shader if you need: FogShaderR.zip —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Oh uh, how do i make it support 1.21?

**Comment by EnderBoy2000** [comment]
Recode the shaderOn 17. Jul 2024, at 16:14, Avisator ***@***.***> wrote:﻿

your shader is outdated and does not support 1.21On 17. Jul 2024, at 15:55, Avisator @.> wrote:﻿ so i have been using better RD for like a while now, and before on a previous version of MCPE(1.20.10), the fog shaders that i was using was completeley working and was fine, but now its not working anymore on the latest version of the game. Can anyone take a look and try to help me on this issue? image.png (view on web) here is the fog shader if you need: FogShaderR.zip —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.>

Oh uh, how do i make it support 1.21?
